# Generated by Django 3.2.23 on 2024-01-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coachprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachProfile',
            new_name='Coach',
        ),
    ]
